### ISSUE TITLE
请问music caption生成相关的代码是还没有公开吗？有其他工作的代码可以参考吗？

### ISSUE THREAD

**Issue by Amber0913** [litwellchi/lvm_datapipe#1]
您好，看到您readme里说music caption生成使用的代码好像还没有整理完，请问这部分代码有其他工作的代码可以参考吗？

**Comment by litwellchi** [comment]
Hello, 是的，music的数据处理部分涉及我们另外的工作，代码暂时还没办法开源。你可以参考论文里的music caption或者借鉴https://github.com/ilaria-manco/muscaps
